version: "3.6"

networks:
  nukr.net:

volumes:
  nukr.postgres:
    name: "nukr-postgres"
    driver: "local"

services:

  api: 
    image: gerardojunior/clojure:stable
    restart: on-failure
    volumes:
      - type: bind
        source: ./
        target: /src
    ports:
      - 3000:3000 # Project port default
      - 12345:12345 # lein relp server
    links:
      - db
    depends_on:
      - db
    networks:
      - nukr.net
  
  db:
    image: postgres:11.3
    restart: on-failure
    volumes:
      - type: volume
        source: nukr.postgres
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
      - type: bind
        source: ./script/init_database.sql
        target: /docker-entrypoint-initdb.d/init_database.sql
    networks:
      - nukr.net
